### ISSUE TITLE
Vol. 5

### ISSUE THREAD

**Issue by ZekyTheWolf** [FssAy/bear100#9]
Getting error: ERROR bear100::app: read_process_memory failed: 0x12B

**Comment by FssAy** [comment]
When I shut up the heavens so that there is no rain, or command locusts to devour the land or send a plague among my people, if my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and I will forgive their sin and will heal their land.

You can still turn to the right path, consider it. 
Cheat outdated.
